services:
  - type: worker
    name: luna-server-bot
    runtime: python
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: CARD_NUMBER
        sync: false
      - key: CARD_HOLDER
        sync: false
      - key: DATABASE_URL
        sync: false
